/// One row per order line for Pedal & Sprocket Bike Co. Feeds the core
/// revenue and order-count measures.
table Sales
	isHidden
	lineageTag: 5d0f6071-c051-4293-9eb4-5f6071829304

	measure 'countrows sales' = COUNTROWS(Sales)
		isHidden
		lineageTag: 6e017182-d162-43a4-8fc5-607182930415

	column order_id
		dataType: int64
		isHidden
		lineageTag: 7f128293-e273-44b5-9ad6-718293041526
		summarizeBy: none
		sourceColumn: order_id

	column order_date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 80239304-f384-45c6-8be7-829304152637
		summarizeBy: none
		sourceColumn: order_date

	column ship_date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 91340415-0495-46d7-9cf8-930415263748
		summarizeBy: none
		sourceColumn: ship_date

	column product_id
		dataType: int64
		isHidden
		lineageTag: a2451526-15a6-47e8-8d09-041526374859
		summarizeBy: none
		sourceColumn: product_id

	column store_id
		dataType: int64
		isHidden
		lineageTag: b3562637-26b7-48f9-9e1a-15263748596a
		summarizeBy: none
		sourceColumn: store_id

	column quantity
		dataType: int64
		isHidden
		lineageTag: c4673748-37c8-490a-8f2b-263748596a7b
		summarizeBy: sum
		sourceColumn: quantity

	column net_amount
		dataType: double
		isHidden
		lineageTag: d5784859-48d9-4a1b-903c-3748596a7b8c
		summarizeBy: sum
		sourceColumn: net_amount

	partition Sales = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZLJCcUwDER78TkCjSwvqSWk/zbiVRYf/kGEh2e05nkCwhWERYlBSB5KA/gQ5vBeTxBTCYE9jJcVsX91OqKJInHyUBuoL5JWETWVkrCHnbxHz4WShuPkTYTqYNjhWmttzSLZVJkkeShLitVflOkoJioE9ZC38neS00qleCa525L3mlqMVjAdtxNBPOi/m5w7gOdWN8wXVwl5Wez0wNyqga5Z7Ja8yxyZuN+lQ3VtjfPk7nk/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"order_id" = _t, #"order_date" = _t, #"ship_date" = _t, #"product_id" = _t, #"store_id" = _t, #"quantity" = _t, #"net_amount" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {{"order_id", Int64.Type}, {"order_date", type datetime}, {"ship_date", type datetime}, {"product_id", Int64.Type}, {"store_id", Int64.Type}, {"quantity", Int64.Type}, {"net_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

