/// One row per order line for Pedal & Sprocket Bike Co. Feeds the core
/// revenue and order-count measures.
table Sales
	isHidden
	lineageTag: 5d0f6071-c051-4293-9eb4-5f6071829304

	measure 'countrows sales' = COUNTROWS(Sales)
		isHidden
		lineageTag: 6e017182-d162-43a4-8fc5-607182930415

	column order_id
		dataType: int64
		isHidden
		lineageTag: 7f128293-e273-44b5-9ad6-718293041526
		summarizeBy: none
		sourceColumn: order_id

	column order_date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 80239304-f384-45c6-8be7-829304152637
		summarizeBy: none
		sourceColumn: order_date

	column ship_date
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 91340415-0495-46d7-9cf8-930415263748
		summarizeBy: none
		sourceColumn: ship_date

	column product_id
		dataType: int64
		isHidden
		lineageTag: a2451526-15a6-47e8-8d09-041526374859
		summarizeBy: none
		sourceColumn: product_id

	column store_id
		dataType: int64
		isHidden
		lineageTag: b3562637-26b7-48f9-9e1a-15263748596a
		summarizeBy: none
		sourceColumn: store_id

	column quantity
		dataType: int64
		isHidden
		lineageTag: c4673748-37c8-490a-8f2b-263748596a7b
		summarizeBy: sum
		sourceColumn: quantity

	column net_amount
		dataType: double
		isHidden
		lineageTag: d5784859-48d9-4a1b-903c-3748596a7b8c
		summarizeBy: sum
		sourceColumn: net_amount

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("sales.csv"), [Delimiter = ",", Encoding = 65001]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true])
				in
				    Promoted
