/// One row per retail store.
table Stores
	lineageTag: e689596a-59ea-4b2c-a14d-48596a7b8c9d

	measure 'Revenue per Store' = DIVIDE([Revenue], DISTINCTCOUNT(Sales[store_id]))
		formatString: $ #,0.00
		lineageTag: 0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c4d

	column store_id
		dataType: int64
		isKey
		lineageTag: 4cefbfc0-bf40-4182-a7a3-aebfc0d1e2f3
		summarizeBy: none
		sourceColumn: store_id

	column store_name
		dataType: string
		lineageTag: 5d00c0d1-c051-4293-88b4-bfc0d1e2f304
		summarizeBy: none
		sourceColumn: store_name

	column region
		dataType: string
		lineageTag: 6e11d1e2-d162-43a4-99c5-c0d1e2f30415
		summarizeBy: none
		sourceColumn: region

	partition Stores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("stores.csv"), [Delimiter = ",", Encoding = 65001]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true])
				in
				    Promoted
