/// One row per retail store.
table Stores
	lineageTag: e689596a-59ea-4b2c-a14d-48596a7b8c9d

	column store_id
		dataType: int64
		isKey
		lineageTag: 4cefbfc0-bf40-4182-a7a3-aebfc0d1e2f3
		summarizeBy: none
		sourceColumn: store_id

	column store_name
		dataType: string
		lineageTag: 5d00c0d1-c051-4293-88b4-bfc0d1e2f304
		summarizeBy: none
		sourceColumn: store_name

	column region
		dataType: string
		lineageTag: 6e11d1e2-d162-43a4-99c5-c0d1e2f30415
		summarizeBy: none
		sourceColumn: region

	partition Stores = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXLJL88rAWIg0y+/qCRDKVYnWskIyPNILErKLwIygvNLocLGQF5oAarqWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"store_id" = _t, #"store_name" = _t, #"region" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {{"store_id", Int64.Type}, {"store_name", type text}, {"region", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

